version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "react-native"
        versions: [">0.71"] # https://github.com/wix/Detox/issues/4154
