name: Detox Android
on:
  push:
    branches:
      - main
      - android
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Install Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run Detox Test(s)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: pixel
          avd-name: Pixel_API_29_AOSP
          script: adb devices

      - name: Install npm dependencies
        run: yarn install --frozen-lockfile

      - name: Install Detox CLI
        run: npm install -g detox-cli

      - name: Build App for Detox
        run: detox build -c android.emu.release

      - name: Run Detox Test(s)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: pixel
          avd-name: Pixel_API_29_AOSP
          script: detox test -c android.emu.release --headless
